name: Update Data

on:
    schedule:
        - cron: '0 */6 * * *'

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: get bad-user-agents
              run: |
                curl -o src/Resources/lists/bad-user-agents.txt https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/refs/heads/master/_generator_lists/bad-user-agents.list
                sed -i 's/\\ / /g' src/Resources/lists/bad-user-agents.txt

            - name: Create PR
              uses: peter-evans/create-pull-request@v7
              with:
                  commit-message: "chore: update data"
                  title: "chore: update data"
                  branch: chore/update-data
                  base: main
                  delete-branch: true
                  body: |
                    This PR updates the data dependencies.
